{{- if .Values.namespace.create -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "k8s-info-collector.fullname" . }}-namespace-creator
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  template:
    metadata:
      name: {{ include "k8s-info-collector.fullname" . }}-namespace-creator
    spec:
      serviceAccountName: default
      restartPolicy: Never
      containers:
      - name: namespace-creator
        image: bitnami/kubectl:latest
        command:
        - "/bin/sh"
        - "-c"
        - |
          kubectl create namespace {{ .Values.serviceAccount.namespace }} || echo "Namespace already exists or cannot be created"
          exit 0
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 