#!/bin/bash
# Nullify Cloud Connector - Interactive Setup Script
# Guides you through configuring the Nullify AWS integration.
#
# Usage:
#   ./setup-aws-integration.sh [--method cloudformation|terraform|helm]

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo -e "${BLUE}${BOLD}"
echo "  ╔══════════════════════════════════════════════╗"
echo "  ║   Nullify Cloud Connector - Setup Wizard     ║"
echo "  ╚══════════════════════════════════════════════╝"
echo -e "${NC}"

# ── Deployment method ─────────────────────────────────────────────
METHOD=""
while [[ $# -gt 0 ]]; do
  case $1 in
    --method) METHOD="$2"; shift 2 ;;
    *) shift ;;
  esac
done

if [[ -z "$METHOD" ]]; then
  echo -e "${BLUE}Choose your deployment method:${NC}"
  echo "  1) CloudFormation  (AWS-native, single command)"
  echo "  2) Terraform       (modular IaC, multi-cluster support)"
  echo "  3) Helm            (Kubernetes-native, requires existing IAM role)"
  echo ""
  read -rp "Enter choice [1-3]: " CHOICE
  case $CHOICE in
    1) METHOD="cloudformation" ;;
    2) METHOD="terraform" ;;
    3) METHOD="helm" ;;
    *) echo -e "${RED}Invalid choice${NC}"; exit 1 ;;
  esac
fi

echo ""
echo -e "${GREEN}Selected: ${METHOD}${NC}"
echo ""

# ── Gather common inputs ──────────────────────────────────────────
echo -e "${BLUE}${BOLD}Step 1: Enter your Nullify configuration${NC}"
echo -e "${YELLOW}(These values are provided on your Nullify configure page)${NC}"
echo ""

read -rp "Customer name: " CUSTOMER_NAME
if [[ ! "$CUSTOMER_NAME" =~ ^[a-zA-Z][a-zA-Z0-9_-]*$ ]]; then
  echo -e "${RED}Error: Customer name must start with a letter and contain only letters, numbers, underscores, hyphens${NC}"
  exit 1
fi

read -rp "External ID: " EXTERNAL_ID
if [[ ${#EXTERNAL_ID} -lt 12 ]]; then
  echo -e "${RED}Error: External ID must be at least 12 characters${NC}"
  exit 1
fi

read -rp "Nullify cross-account role ARN: " NULLIFY_ROLE_ARN
if [[ ! "$NULLIFY_ROLE_ARN" =~ ^arn:aws:iam::[0-9]{12}:role/.+$ ]]; then
  echo -e "${RED}Error: Invalid IAM role ARN format${NC}"
  exit 1
fi

read -rp "AWS region [ap-southeast-2]: " AWS_REGION
AWS_REGION="${AWS_REGION:-ap-southeast-2}"

read -rp "S3 bucket name (optional, press Enter to skip): " S3_BUCKET

read -rp "KMS key ARN (optional, press Enter to skip): " KMS_KEY_ARN

echo ""
echo -e "${BLUE}${BOLD}Step 2: Kubernetes integration${NC}"
read -rp "Enable EKS/Kubernetes integration? [y/N]: " ENABLE_K8S
ENABLE_K8S="${ENABLE_K8S:-n}"

EKS_CLUSTER_ARNS=()
EKS_OIDC_URL=""
if [[ "$ENABLE_K8S" =~ ^[yY]$ ]]; then
  if [[ "$METHOD" == "cloudformation" ]]; then
    read -rp "EKS OIDC provider URL (without https://): " EKS_OIDC_URL
  else
    echo "Enter EKS cluster ARNs (one per line, empty line to finish):"
    while true; do
      read -rp "  Cluster ARN: " ARN
      [[ -z "$ARN" ]] && break
      EKS_CLUSTER_ARNS+=("$ARN")
    done
    if [[ ${#EKS_CLUSTER_ARNS[@]} -eq 0 ]]; then
      echo -e "${RED}Error: At least one cluster ARN is required${NC}"
      exit 1
    fi
  fi
fi

# ── Generate configuration ────────────────────────────────────────
echo ""
echo -e "${BLUE}${BOLD}Step 3: Generating configuration...${NC}"
echo ""

case $METHOD in
  cloudformation)
    PARAMS="ParameterKey=CustomerName,ParameterValue=${CUSTOMER_NAME}"
    PARAMS="$PARAMS ParameterKey=ExternalID,ParameterValue=${EXTERNAL_ID}"
    PARAMS="$PARAMS ParameterKey=CrossAccountRoleArn,ParameterValue=${NULLIFY_ROLE_ARN}"
    PARAMS="$PARAMS ParameterKey=AWSRegion,ParameterValue=${AWS_REGION}"

    if [[ -n "$S3_BUCKET" ]]; then
      PARAMS="$PARAMS ParameterKey=NullifyS3Bucket,ParameterValue=${S3_BUCKET}"
    fi
    if [[ -n "$KMS_KEY_ARN" ]]; then
      PARAMS="$PARAMS ParameterKey=NullifyKMSKeyArn,ParameterValue=${KMS_KEY_ARN}"
    fi
    if [[ "$ENABLE_K8S" =~ ^[yY]$ ]]; then
      PARAMS="$PARAMS ParameterKey=EnableEKSIntegration,ParameterValue=true"
      PARAMS="$PARAMS ParameterKey=EKSOidcProviderURL,ParameterValue=${EKS_OIDC_URL}"
    fi

    TEMPLATE_PATH="${REPO_ROOT}/aws-integration-setup/cloudformation/nullify-cloudformation-template.json"

    echo -e "${GREEN}Run this command to deploy:${NC}"
    echo ""
    echo -e "${YELLOW}aws cloudformation create-stack \\"
    echo "  --stack-name nullify-integration-${CUSTOMER_NAME} \\"
    echo "  --template-body file://${TEMPLATE_PATH} \\"
    echo "  --capabilities CAPABILITY_NAMED_IAM \\"
    echo "  --parameters ${PARAMS}${NC}"
    ;;

  terraform)
    TFVARS_PATH="${REPO_ROOT}/aws-integration-setup/terraform/terraform.tfvars"

    cat > "$TFVARS_PATH" <<EOF
# Generated by setup-aws-integration.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
customer_name   = "${CUSTOMER_NAME}"
external_id     = "${EXTERNAL_ID}"
nullify_role_arn = "${NULLIFY_ROLE_ARN}"
aws_region      = "${AWS_REGION}"
EOF

    if [[ -n "$S3_BUCKET" ]]; then
      echo "s3_bucket_name  = \"${S3_BUCKET}\"" >> "$TFVARS_PATH"
    fi
    if [[ -n "$KMS_KEY_ARN" ]]; then
      echo "kms_key_arn     = \"${KMS_KEY_ARN}\"" >> "$TFVARS_PATH"
    fi
    if [[ "$ENABLE_K8S" =~ ^[yY]$ ]]; then
      echo "enable_kubernetes_integration = true" >> "$TFVARS_PATH"
      echo -n "eks_cluster_arns = [" >> "$TFVARS_PATH"
      for i in "${!EKS_CLUSTER_ARNS[@]}"; do
        [[ $i -gt 0 ]] && echo -n ", " >> "$TFVARS_PATH"
        echo -n "\"${EKS_CLUSTER_ARNS[$i]}\"" >> "$TFVARS_PATH"
      done
      echo "]" >> "$TFVARS_PATH"
    fi

    echo -e "${GREEN}Generated: ${TFVARS_PATH}${NC}"
    echo ""
    echo -e "${GREEN}Run these commands to deploy:${NC}"
    echo ""
    echo -e "${YELLOW}cd ${REPO_ROOT}/aws-integration-setup/terraform"
    echo "terraform init"
    echo "terraform plan"
    echo "terraform apply${NC}"
    ;;

  helm)
    VALUES_PATH="${REPO_ROOT}/helm-charts/nullify-k8s-collector/values-custom.yaml"

    cat > "$VALUES_PATH" <<EOF
# Generated by setup-aws-integration.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
collector:
  clusterName: "${CUSTOMER_NAME}"
EOF

    if [[ -n "$S3_BUCKET" ]]; then
      cat >> "$VALUES_PATH" <<EOF
  s3BucketName: "${S3_BUCKET}"
  awsRegion: "${AWS_REGION}"
EOF
    fi
    if [[ -n "$KMS_KEY_ARN" ]]; then
      echo "  kmsKeyArn: \"${KMS_KEY_ARN}\"" >> "$VALUES_PATH"
    fi

    cat >> "$VALUES_PATH" <<EOF

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "REPLACE_WITH_IAM_ROLE_ARN_AFTER_CREATION"
EOF

    echo -e "${GREEN}Generated: ${VALUES_PATH}${NC}"
    echo ""
    echo -e "${YELLOW}Note: You must first create the IAM role using CloudFormation or Terraform,${NC}"
    echo -e "${YELLOW}then update the role ARN in ${VALUES_PATH}${NC}"
    echo ""
    echo -e "${GREEN}Run these commands to deploy:${NC}"
    echo ""
    echo -e "${YELLOW}helm install nullify-collector ${REPO_ROOT}/helm-charts/nullify-k8s-collector \\"
    echo "  -f ${VALUES_PATH} \\"
    echo "  -n nullify --create-namespace${NC}"
    ;;
esac

echo ""
echo -e "${BLUE}${BOLD}Step 4: Post-deployment validation${NC}"
echo ""
echo -e "After deploying, run the validation script:"
echo -e "${YELLOW}${SCRIPT_DIR}/validate-deployment.sh --role-arn <YOUR_ROLE_ARN> --external-id ${EXTERNAL_ID}${NC}"
if [[ "$ENABLE_K8S" =~ ^[yY]$ ]]; then
  echo -e "${YELLOW}  --check-k8s --namespace nullify${NC}"
fi
echo ""
echo -e "${GREEN}Setup complete!${NC}"
