{{- if .Values.serviceAccount.create -}}
{{- $provider := .Values.cloudProvider | default "aws" -}}
{{- $annotations := dict -}}
{{- range $k, $v := .Values.serviceAccount.annotations -}}
  {{- if eq $k "eks.amazonaws.com/role-arn" -}}
    {{- if eq $provider "aws" -}}
      {{- $_ := set $annotations $k $v -}}
    {{- end -}}
  {{- else if eq $k "iam.gke.io/gcp-service-account" -}}
    {{- if eq $provider "gcp" -}}
      {{- $_ := set $annotations $k $v -}}
    {{- end -}}
  {{- else -}}
    {{- $_ := set $annotations $k $v -}}
  {{- end -}}
{{- end -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.serviceAccount.namespace }}
  labels:
    {{- include "k8s-collector.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
