name: Release Helm Chart

on:
  push:
    branches: [ main ]
    paths:
      - 'aws-integration-setup/charts/**'
      - '.github/workflows/helm-release.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.14.0

    - name: Get Chart Version
      id: version
      run: |
        VERSION=$(grep '^version:' aws-integration-setup/charts/nullify-k8s-collector/Chart.yaml | awk '{print $2}' | tr -d '"')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Using Chart.yaml version: $VERSION"

    - name: Add Helm repos (if chart has dependencies)
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami || true
        helm repo update || true

    - name: Package Helm Chart
      run: |
        # Create docs directory if it doesn't exist
        mkdir -p docs
        
        # Package the chart
        helm package aws-integration-setup/charts/nullify-k8s-collector -d docs/
        
        # Generate/update the index
        helm repo index docs/ --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.14.0

    - name: Validate Helm Chart
      run: |
        helm lint aws-integration-setup/charts/nullify-k8s-collector
        helm template aws-integration-setup/charts/nullify-k8s-collector --debug
